name: flutter_learning_app
description: "Akshara: Multi-language learning app for Telugu, Hindi, and English."
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_tts: ^4.0.2
  provider: ^6.1.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0
  flutter_launcher_icons: ^0.13.1

flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/icon/app_logo.png"
  min_sdk_android: 21
  adaptive_icon_background: "#1E122A"
  adaptive_icon_foreground: "assets/icon/app_logo.png"

flutter:
  uses-material-design: true

  assets:
    - assets/data/
    - assets/icon/
    
