dependencies:
  flutter:
    sdk: flutter
  flutter_tts: ^4.0.2

flutter:
  uses-material-design: true
  assets:
    - assets/data/
    - assets/images/step2_words/
    - assets/images/step4_gunintalu/
    
